services:
  appserver:
    type: php:8.1
    build_as_root:
      - /app/scripts/settings.sh
  mailhog:
    type: mailhog:v1.0.1
    portforward: true
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin:5.1
    hosts:
      - database

events:
  post-rebuild:
    - appserver: /app/scripts/additions.sh

tooling:
  drupal:
    service: appserver
    cmd: drupal
    dir: /app
  composer:
    service: appserver
    cmd: composer
    dir: /app/web
