services:
  appserver:
    type: php:8.2
    xdebug: true
  mailhog:
    type: mailhog:v1.0.1
    portforward: true
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin:5.1
    hosts:
      - database

events:
  post-rebuild:
    - chmod 777 /app/web/sites/default/settings.php
    - appserver: /app/scripts/additions.sh
    - chmod 444 /app/web/sites/default/settings.php

tooling:
  drush:
    service: appserver
    cmd: /app/web/vendor/drush/drush/drush --root=/app/web
