services:
  appserver:
    type: php:8.1
  mailhog:
    type: mailhog:v1.0.1
    portforward: true
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin:5.1
    hosts:
      - database

events:
  post-rebuild:
    - appserver: /app/scripts/additions.sh
